create table note (
	note_id bigint not null primary key generated by default as identity,
	article_id bigint not null,
	note text not null,
	author text not null,
	created_at timestamptz not null default now(),
	edited_by text,
	edited_at timestamptz,
	answer_on bigint,
	voted_up integer,
	voted_down integer,
	hided boolean not null
);

insert
into note (
    article_id,
    note,
    author,
    hided
)
values
(
    1,
    'just simple note',
    'michalkubrak.90@gmail.com',
    FALSE
);

insert
into note (
    article_id,
    note,
    author,
    hided
)
values
(
    2,
    'just another simple note',
    'michalkubrak.90@gmail.com',
    FALSE
);