create table note (
	note_id bigint not null primary key generated by default as identity,
	article_id bigint not null,
	note text not null,
	author text not null,
	created_at timestamptz not null default now(),
	edited_by text,
	edited_at timestamptz,
	answer_on bigint,
	voted_up integer,
	voted_down integer,
	hided boolean not null
);